In [17]:
import pandas as pd

In [18]:
with open("test.txt",'r') as test:
    lines = test.readlines()
    line=lines[0]
    line = lines[0]
    arr = line.split(', ')
    arr[0] = arr[0][1:]
    arr[-1] = arr[-1][:-1]
    testids = [int(s) for s in arr]

In [19]:
with open("train.txt",'r') as train:
    lines = train.readlines()
    line=lines[0]
    line = lines[0]
    arr = line.split(', ')
    arr[0] = arr[0][1:]
    arr[-1] = arr[-1][:-1]
    trainids = [int(s) for s in arr]

In [20]:
with open("valn.txt",'r') as valn:
    lines = valn.readlines()
    line=lines[0]
    line = lines[0]
    arr = line.split(', ')
    arr[0] = arr[0][1:]
    arr[-1] = arr[-1][:-1]
    valids = [int(s) for s in arr]

In [21]:
with open("final_bad_ids.txt",'r') as bad:
    lines = bad.readlines()
    line=lines[0]
    line = lines[0]
    arr = line.split(', ')
    arr[0] = arr[0][1:]
    arr[-1] = arr[-1][:-1]
    badids = [int(s) for s in arr]

In [8]:
df = pd.read_excel("behaviour_simulation_train.xlsx")

In [22]:
test_df = df[df['id'].isin(testids)]
train_df = df[df['id'].isin(trainids)]
val_df = df[df['id'].isin(valids)]
bad_df = df[df['id'].isin(badids)]

In [23]:
test_df.head()

,id,date,likes,content,username,media,inferred company
4,5,2018-10-19 14:30:46,41,Congratulations to Pauletha Butts of <mention>...,BGISD,[Photo(previewUrl='https://pbs.twimg.com/media...,independent
11,12,2020-11-18 00:07:02,0,#NetZeroHomes: learn the best way to get to ze...,MitsubishiHVAC,[Photo(previewUrl='https://pbs.twimg.com/media...,trane
22,23,2018-09-11 14:23:02,120,"Tournaments come and go, but the pictures are ...",GettySport,[Photo(previewUrl='https://pbs.twimg.com/media...,getty images
30,31,2020-11-10 03:00:26,567,Monster Hunter Rise Concept Art: Great Izuchi....,MHinfo_en,[Photo(previewUrl='https://pbs.twimg.com/media...,monster
31,32,2018-11-29 22:11:56,1,"With our #SalesDevelopmentProgram, you'll lear...",UnitedRentals,[Photo(previewUrl='https://pbs.twimg.com/media...,united rentals

In [24]:
train_df.head()

,id,date,likes,content,username,media,inferred company
0,1,2020-12-12 00:47:00,1,"Spend your weekend morning with a Ham, Egg, an...",TimHortonsPH,[Photo(previewUrl='https://pbs.twimg.com/media...,tim hortons
1,2,2018-06-30 10:04:20,2750,Watch rapper <mention> freestyle for over an H...,IndyMusic,[Photo(previewUrl='https://pbs.twimg.com/media...,independent
2,3,2020-09-29 19:47:28,57,Canadian Armenian community demands ban on mil...,CBCCanada,[Photo(previewUrl='https://pbs.twimg.com/media...,cbc
3,4,2020-10-01 11:40:09,152,"1st in Europe to be devastated by COVID-19, It...",MKWilliamsRome,[Photo(previewUrl='https://pbs.twimg.com/media...,williams
5,6,2020-11-15 16:01:08,525,An 85-year-old primary school in Shanghai has ...,cnni,[Video(thumbnailUrl='https://pbs.twimg.com/amp...,cnn

In [25]:
val_df.head()

,id,date,likes,content,username,media,inferred company
6,7,2019-10-24 10:51:03,0,LASU Celebrates New Dawn Of Unbroken Peace As ...,IndependentNGR,[Photo(previewUrl='https://pbs.twimg.com/media...,independent
12,13,2020-03-01 15:48:46,672,"The US-Taliban agreement, which sets into moti...",CNN,[Video(thumbnailUrl='https://pbs.twimg.com/med...,cnn
24,25,2020-07-19 00:07:00,78,Many people are understandably anxious to get ...,MayoClinic,[Photo(previewUrl='https://pbs.twimg.com/media...,mayo clinic
26,27,2018-09-26 16:42:17,961,ALSO NOW (yes it's wild here today): Sen Merkl...,LisaDNews,[Photo(previewUrl='https://pbs.twimg.com/media...,desjardins
38,39,2020-03-11 20:15:08,4,Toyota Motor North America Chief Diversity Off...,ToyotaSD,[Photo(previewUrl='https://pbs.twimg.com/media...,toyota

In [26]:
bad_df.head()

,id,date,likes,content,username,media,inferred company
190,191,2020-07-09 17:48:42,357,Lucas Digne's pass 🎯\nRicharlison's finish 👌\n...,primevideosport,[Video(thumbnailUrl='https://pbs.twimg.com/med...,amazon
365,366,2018-10-19 16:11:28,1195,Sicko Mode video looks nuts. <hyperlink>,austinxwill,[Video(thumbnailUrl='https://pbs.twimg.com/ext...,williams
465,466,2018-07-11 19:30:44,124,GOAL! Perisic 68' vs England #AstroWC2018 <hyp...,stadiumastro,[Video(thumbnailUrl='https://pbs.twimg.com/med...,astro
750,751,2020-12-13 00:36:17,67,One of my favourite mashups I’ve ever recorded...,thisisaviva,[Video(thumbnailUrl='https://pbs.twimg.com/ext...,aviva
900,901,2018-02-23 17:17:35,676,Kim Boutin has become a regular on the podium—...,CBCOlympics,[Video(thumbnailUrl='https://pbs.twimg.com/med...,cbc

In [28]:
train_df.to_csv("train.csv", index=False)
test_df.to_csv("test.csv", index=False)
val_df.to_csv("val.csv", index=False)
bad_df.to_csv("bad_vids.csv", index=False)